= Bibliothèque Botly pour plateforme Arduino =

Cette bibliothèque a pour but de faciliter le pilotage du robot Botly

== License ==

Cette bibliothèque est distribuée sous licence Creative Commons  CC-BY-NC-SA

Vous êtes autorisé à :

Partager — copier, distribuer et communiquer le matériel par tous moyens et sous
tous formats Adapter — remixer, transformer et créer à partir du matériel
L'Offrant ne peut retirer les autorisations concédées par la licence tant que
vous appliquez les termes de cette licence.

Attribution — Vous devez créditer l'Œuvre, intégrer un lien vers la licence et
indiquer si des modifications ont été effectuées à l'Oeuvre. Vous devez indiquer
ces informations par tous les moyens raisonnables, sans toutefois suggérer que
l'Offrant vous soutient ou soutient la façon dont vous avez utilisé son Oeuvre.

Pas d’Utilisation Commerciale — Vous n'êtes pas autorisé à faire un usage
commercial de cette Oeuvre, tout ou partie du matériel la composant.

Partage dans les Mêmes Conditions — Dans le cas où vous effectuez un remix, que
vous transformez, ou créez à partir du matériel composant l'Oeuvre originale,
vous devez diffuser l'Oeuvre modifiée dans les même conditions, c'est à dire
avec la même licence avec laquelle l'Oeuvre originale a été diffusée.
